
CREATE DATABASE IF NOT EXISTS elstat CHARACTER SET utf8mb4;
USE elstat;

CREATE TABLE IF NOT EXISTS country (
    id INT NOT NULL AUTO_INCREMENT 
    c VARCHAR(50) NOT NULL,
    tourists INT,
    percentage FLOAT,
    airplane INT,
    train INT,
    ship INT,
    car INT,
    PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS month (
	m VARCHAR(10) NOT NULL,
    c VARCHAR(50) NOT NULL,
    PRIMARY KEY (m, c),
    CONSTRAINT nation FOREIGN KEY (c) REFERENCES country(c) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS year (
	y INT NOT NULL,
    m VARCHAR(10) NOT NULL,
    PRIMARY KEY (y, m),
    CONSTRAINT interval FOREIGN KEY (m) REFERENCES month(m) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB;
